### ISSUE TITLE
pfBlocker - DNSLB - service disabled after setup

### ISSUE THREAD

**Issue by yboujraf** [mikael-andre/pfSense#1]
Dear,

After following the setup , I have my  DNSBL service disabled.

**Version of pfSense**

`
Version | 2.4.4-RELEASE (amd64) built on Thu Sep 20 09:03:12 EDT 2018 FreeBSD 11.2-RELEASE-p3
`

**Version of the pfBlockerNG**

`pfBlockerNG | net | 2.1.4_13 | 

pfBlockerNG is the Next Generation of pfBlocker.Manage IPv4/v6 List Sources into 'Deny, Permit or Match' formats.GeoIP database by MaxMind Inc. (GeoLite2 Free version).De-Duplication, Suppression, and Reputation enhancements.Provision to download from diverse List formats.Advanced Integration for Proofpoint ET IQRisk IP Reputation Threat Sources.Domain Name (DNSBL) blocking via Unbound DNS Resolver.	

Package Dependencies:  lighttpd-1.4.49 	  whois-5.2.17 	  GeoIP-1.6.12 	  grepcidr-2.0 	  aggregate-1.6_1 	  php72-7.2.10 	 php72-intl-7.2.10`

**Please find a copy of the log** 

` UPDATE PROCESS START [ 11/20/18 15:41:21 ]

===[  DNSBL Process  ]================================================

[ EasyListWOElements ]	 exists.
[ BBcan177Domains ]	 exists.
[ BBcan177Threats ]	 exists.
[ YoYo ]		 exists.
[ SWC ]			 exists.
[ Adaway ]		 exists.
[ AdBlockPlus ]		 exists.
[ MalwareJustDomains ]	 exists.
[ MicrosoftDomains ]	 exists.
[ YouTubeVideoAds ]	 exists.
[ MalwareImmortalDomains ] exists.
[ MalwareHosts ]	 exists.
[ Malvertising ]	 exists.
[ hpHostsAds ]		 exists.
[ Cameleon ]		 exists.
[ RansomwareDomainBlocklist ] exists.
[ Cryptolocker ]	 exists.
[ DNSBLMalicious ]	 exists.
[ OpenFish ]		 exists.
[ Phishtank ]		 exists.
[ MoneroMiner ]		 exists.
[ spam404 ]		 exists.
[ Malc0de ]		 exists.
[ AbuseCh ]		 exists.
[ StevenBlack ]		 exists.
[ DisconnectTracking ]	 exists.
[ DisconnectAds ]	 exists.
[ Princeton ]		 exists.
[ ISClow ]		 exists.
[ DShieldMedium ]	 exists.
[ DShieldHigh ]		 exists.
[ WindowsTelemetry ]	 exists.
[ Quidsup ]		 exists.
[ AdGuardDNS ]		 exists.
[ HostsFile ]		 exists.
[ AirelleHrsk ]		 exists.
[ PrigentMalware ]	 exists.
[ PrigentPhishing ]	 exists.
[ ShallaMal ]		 exists. [ 11/20/18 15:41:22 ]
[ ISCmedium ]		 exists.
[ ISChigh ]		 exists.
[ StevenBlackAds ]	 exists.
[ HostsFileExp ]	 exists.
[ HostsFileEmd ]	 exists.
[ HostsFilePsh ]	 exists.
[ HostsFileGrm ]	 exists.
[ StevenBlackKAdHosts ]	 exists.
[ StevenBlackSpam ]	 exists.
[ W3KBL ]		 exists.
[ BillStearns ]		 exists.
[ Spammers ]		 exists.
[ Dawsey21 ]		 exists.
[ Vokins ]		 exists.
[ AirelleTrc ]		 exists.
[ PrigentAds ]		 exists.
[ StevenBlackHosts ]	 exists.
[ ChefKoch1 ]		 exists.
[ ChefKoch2 ]		 exists.
[ SamsungSmart ]	 exists.
[ EasyPrivacy2 ]	 exists.
[ GiftCardKiller ]	 exists.
[ DNSBL_IP ]		 Updating aliastable... 
  no changes.
  Total IP count = 1818

** DNSBL Disabled **

===[  Continent Process  ]============================================

===[  IPv4 Process  ]=================================================

[ Firehol_Level3 ]	 exists.
[ BinaryDefense_BanList ] exists.
[ Emerging ]		 exists.

===[  Aliastables / Rules  ]==========================================

No changes to Firewall rules, skipping Filter Reload
No Changes to Aliases, Skipping pfctl Update

 UPDATE PROCESS ENDED [ 11/20/18 15:41:24 ]
`
**Dashboard Status**

![2018-11-20 2](https://user-images.githubusercontent.com/6151258/48781041-7a617380-ecdb-11e8-9c86-f61305e7bf68.png)

**Firewall pfBlockerNG - DNSLB settings**

![2018-11-20 4](https://user-images.githubusercontent.com/6151258/48781386-36bb3980-ecdc-11e8-810a-b045d3f9fbdb.png)

I hope it could help you.

Best Regards,
Youssef

**Comment by marcoczen** [comment]
Hi ... its been a while ... but how did u solve your problem ? Was one of your interfaces disabled by accident ?

**Comment by mikael-andre** [comment]
Hi guys,

Some URL feeds have not been maintain. I updated https://github.com/mikael-andre/pfSense/wiki/HOWTO-pfSense-pfBlockerNG.
