### ISSUE TITLE
Update 6. DNSBL in HOWTO+pfSense+pfBlockerNG

### ISSUE THREAD

**Issue by latchee** [mikael-andre/pfSense#3]
Some list are not working anymore. Here are my updates:

 [ DNSBL_DNSBlockListGroup - Cryptolocker ] Restricted for commercial use, can ask for non profit / personal use > sales@bambenekconsulting.com
 [ DNSBL_DNSBlockListGroup - CoinlistBrowser ] https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
 [ DNSBL_DNSBlockListGroup - Quidsup ] https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
 [ DNSBL_DNSBlockListGroup - HostsFile ] Malwarebytes does not offer this list anymore
 [ DNSBL_DNSBlockListGroup - CoinlistHost ] https://zerodot1.gitlab.io/CoinBlockerLists/hosts
 [ DNSBL_DNSBlockListGroup - CoinlistHost_optional ] https://zerodot1.gitlab.io/CoinBlockerLists/hosts_optional
 [ DNSBL_DNSBlockListGroup - HostsFileExp ] Malwarebytes does not offer this list anymore
 [ DNSBL_DNSBlockListGroup - HostsFileEmd ] Malwarebytes does not offer this list anymore
 [ DNSBL_DNSBlockListGroup - HostsFilePsh ] Malwarebytes does not offer this list anymore
 [ DNSBL_DNSBlockListGroup - HostsFileGrm ] Malwarebytes does not offer this list anymore 
 [ DNSBL_DNSBlockListGroup - GiftCardKiller ] https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/Mega%20Untrusted%20Hosts%20Blocker.txt

**Comment by mikael-andre** [comment]
Hi Latchee,

Thank you for the update.

**Comment by mikael-andre** [comment]
Url updated : https://github.com/mikael-andre/pfSense/wiki/HOWTO-pfSense-pfBlockerNG
