### ISSUE TITLE
Infinity Loads all never finishes the updates 

### ISSUE THREAD

**Issue by underling3311** [mikael-andre/pfSense#4]
I have 6 computers all the same. I have a pfsense firewall with pfblocker installed. Last few months ago there was an update that really small. 1 -2 line of code changed. I looked because I had problem with an update. After that day, I have been having these problems with many pfsense firewalls on these machine specs. Some reason after pressing an update of pfblocker it never finishes the update. You can come back 24 hours later and not have it finished. The only way to stop it by restart it then after restarted it still shows there's an update. If your lucky it has update but you have try it 10 times or more. Just luck I guess. 

New Pfsense
I have created a new pfsense firewall, same machine different ssd. (have 6 machines). I thought the pfsense had a problem or something. After creating a new pfblocker everything was normal clean install/ pfsense. Few weeks or month later, theres an update. Same-thing as above Infinity Loads and never finishes. 

Specs for CPU

Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz - (2013)
Current: 3200 MHz, Max: 3201 MHz
4 CPUs: 1 package(s) x 4 core(s)
AES-NI CPU Crypto: Yes (active)

*This were it gets up to but stops.*

>>>Upgrading pfSense-pkg-pfBlockerNG-devel... 
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

>>>Installed packages to be UPGRADED:
	pfSense-pkg-pfBlockerNG-devel: 3.0.0_8 -> 3.0.0_10 [pfSense]

>>>Number of packages to be upgraded: 1

>>>2 MiB to be downloaded.
[1/1] Fetching pfSense-pkg-pfBlockerNG-devel-3.0.0_10.txz: .......... done
Checking integrity... done (0 conflicting)
[1/1] Upgrading pfSense-pkg-pfBlockerNG-devel from 3.0.0_8 to 3.0.0_10...
[1/1] Extracting pfSense-pkg-pfBlockerNG-devel-3.0.0_10: .......... done
Removing pfBlockerNG-devel components...
Menu items... done.
Services... done.
Loading package instructions...
Removing pfBlockerNG... All customizations/data will be retained... done.

**Comment by mikael-andre** [comment]
Hi MrWaste,

Sorry for the long time, I changed my personal firewall to another modele, Fortigate.
Do you have the issue ? Did you try to disable some feeds ?

**Comment by mikael-andre** [comment]
Hi @MrWaste ,

I made an update of URL feeds.
Could you please try again ?

Sorry for the delay.

**Comment by underling3311** [comment]
I don't remember on how I fixed this. Its fixed now. Been to long.
